# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doordash.api/client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'doordash.api/client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64oordash.api/client.proto\x12\x13\x64oordash.api.client\x1a google/protobuf/descriptor.proto:2\n\x08optional\x12\x1d.google.protobuf.FieldOptions\x18\xb2\xbd\xf1\x05 \x01(\x08:2\n\x08nullable\x12\x1d.google.protobuf.FieldOptions\x18\xb3\xbd\xf1\x05 \x01(\x08:;\n\x0f\x66ields_optional\x12\x1f.google.protobuf.MessageOptions\x18\xb3\xbd\xf1\x05 \x01(\x08\x42y\n\x10\x63om.doordash.apiB\x14\x43lientFieldRuleProtoP\x01ZCgithub.com/doordash/services-protobuf/generated/doordash.api.client\xf8\x01\x01\xa2\x02\x04\x44\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doordash.api.client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.doordash.apiB\024ClientFieldRuleProtoP\001ZCgithub.com/doordash/services-protobuf/generated/doordash.api.client\370\001\001\242\002\004DAPI'
# @@protoc_insertion_point(module_scope)
