# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doordash.api/field_injection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'doordash.api/field_injection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"doordash.api/field_injection.proto\x12\x0c\x64oordash.api\"5\n\rInjectHeaders\x12$\n\x06inject\x18\x01 \x03(\x0b\x32\x14.doordash.api.Inject\"7\n\x0e\x46orwardHeaders\x12%\n\x07\x66orward\x18\x01 \x03(\x0b\x32\x14.doordash.api.Inject\"L\n\x06Inject\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x33\n\x0einjection_rule\x18\x02 \x01(\x0b\x32\x1b.doordash.api.InjectionRule\"h\n\rInjectionRule\x12\x11\n\tcast_type\x18\x01 \x01(\t\x12\x15\n\rdefault_value\x18\x02 \x01(\t\x12-\n\x0b\x63onversions\x18\x03 \x03(\x0e\x32\x18.doordash.api.Conversion*L\n\x08InjectId\x12\t\n\x05\x43X_ID\x10\x00\x12\t\n\x05\x44X_ID\x10\x01\x12\t\n\x05MX_ID\x10\x02\x12\x0b\n\x07USER_ID\x10\x03\x12\x12\n\x0e\x44\x45VELOPER_UUID\x10\x04*)\n\nConversion\x12\x11\n\rDECODE_BASE64\x10\x00\x12\x08\n\x04JSON\x10\x01\x42q\n\x10\x63om.doordash.apiB\x13\x46ieldInjectionProtoP\x01Z<github.com/doordash/services-protobuf/generated/doordash.api\xf8\x01\x01\xa2\x02\x04\x44\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doordash.api.field_injection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.doordash.apiB\023FieldInjectionProtoP\001Z<github.com/doordash/services-protobuf/generated/doordash.api\370\001\001\242\002\004DAPI'
  _globals['_INJECTID']._serialized_start=348
  _globals['_INJECTID']._serialized_end=424
  _globals['_CONVERSION']._serialized_start=426
  _globals['_CONVERSION']._serialized_end=467
  _globals['_INJECTHEADERS']._serialized_start=52
  _globals['_INJECTHEADERS']._serialized_end=105
  _globals['_FORWARDHEADERS']._serialized_start=107
  _globals['_FORWARDHEADERS']._serialized_end=162
  _globals['_INJECT']._serialized_start=164
  _globals['_INJECT']._serialized_end=240
  _globals['_INJECTIONRULE']._serialized_start=242
  _globals['_INJECTIONRULE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
