# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doordash.api/field_behavior.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'doordash.api/field_behavior.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!doordash.api/field_behavior.proto\x12\x0c\x64oordash.api\")\n\x10PiiHandlingRules\x12\x15\n\rmask_entirely\x18\x01 \x01(\x08*+\n\rFieldBehavior\x12\x0c\n\x08OPTIONAL\x10\x00\x12\x0c\n\x08REQUIRED\x10\x01*D\n\x1aRequiredFieldValueBehavior\x12\x08\n\x04OMIT\x10\x00\x12\x11\n\rDEFAULT_VALUE\x10\x01\x12\t\n\x05THROW\x10\x02\x42p\n\x10\x63om.doordash.apiB\x12\x46ieldBehaviorProtoP\x01Z<github.com/doordash/services-protobuf/generated/doordash.api\xf8\x01\x01\xa2\x02\x04\x44\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doordash.api.field_behavior_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.doordash.apiB\022FieldBehaviorProtoP\001Z<github.com/doordash/services-protobuf/generated/doordash.api\370\001\001\242\002\004DAPI'
  _globals['_FIELDBEHAVIOR']._serialized_start=94
  _globals['_FIELDBEHAVIOR']._serialized_end=137
  _globals['_REQUIREDFIELDVALUEBEHAVIOR']._serialized_start=139
  _globals['_REQUIREDFIELDVALUEBEHAVIOR']._serialized_end=207
  _globals['_PIIHANDLINGRULES']._serialized_start=51
  _globals['_PIIHANDLINGRULES']._serialized_end=92
# @@protoc_insertion_point(module_scope)
