# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doordash.api/field_validate.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'doordash.api/field_validate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!doordash.api/field_validate.proto\x12\x15\x64oordash.api.validate\x1a google/protobuf/descriptor.proto\"R\n\nFieldRules\x12<\n\rmissing_value\x18\x01 \x01(\x0b\x32#.doordash.api.validate.MissingValueH\x00\x42\x06\n\x04rule\"I\n\x0cMissingValue\x12\x39\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32).doordash.api.validate.MissingValueAction*A\n\x12MissingValueAction\x12\n\n\x06IGNORE\x10\x00\x12\x15\n\x11USE_DEFAULT_VALUE\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02:R\n\x05rules\x12\x1d.google.protobuf.FieldOptions\x18\x8c\xbe\xf1\x05 \x01(\x0b\x32!.doordash.api.validate.FieldRulesBp\n\x10\x63om.doordash.apiB\x12\x46ieldValidateProtoP\x01Z<github.com/doordash/services-protobuf/generated/doordash.api\xf8\x01\x01\xa2\x02\x04\x44\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doordash.api.field_validate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.doordash.apiB\022FieldValidateProtoP\001Z<github.com/doordash/services-protobuf/generated/doordash.api\370\001\001\242\002\004DAPI'
  _globals['_MISSINGVALUEACTION']._serialized_start=253
  _globals['_MISSINGVALUEACTION']._serialized_end=318
  _globals['_FIELDRULES']._serialized_start=94
  _globals['_FIELDRULES']._serialized_end=176
  _globals['_MISSINGVALUE']._serialized_start=178
  _globals['_MISSINGVALUE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
