# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kotlin_grpc_service import message_pb2 as kotlin__grpc__service_dot_message__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kotlin_grpc_service/message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KotlinGRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessageForSQSExample = channel.unary_unary(
                '/doordash_kotlin_grpc_service.KotlinGRPCService/CreateMessageForSQSExample',
                request_serializer=kotlin__grpc__service_dot_message__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=kotlin__grpc__service_dot_message__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.GetMessagesFromSQSExample = channel.unary_unary(
                '/doordash_kotlin_grpc_service.KotlinGRPCService/GetMessagesFromSQSExample',
                request_serializer=kotlin__grpc__service_dot_message__pb2.EmptyRequest.SerializeToString,
                response_deserializer=kotlin__grpc__service_dot_message__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.GetMessageStream = channel.unary_stream(
                '/doordash_kotlin_grpc_service.KotlinGRPCService/GetMessageStream',
                request_serializer=kotlin__grpc__service_dot_message__pb2.GetMessageStreamRequest.SerializeToString,
                response_deserializer=kotlin__grpc__service_dot_message__pb2.GetMessageStreamResponse.FromString,
                _registered_method=True)


class KotlinGRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMessageForSQSExample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessagesFromSQSExample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KotlinGRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMessageForSQSExample': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessageForSQSExample,
                    request_deserializer=kotlin__grpc__service_dot_message__pb2.CreateMessageRequest.FromString,
                    response_serializer=kotlin__grpc__service_dot_message__pb2.EmptyResponse.SerializeToString,
            ),
            'GetMessagesFromSQSExample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessagesFromSQSExample,
                    request_deserializer=kotlin__grpc__service_dot_message__pb2.EmptyRequest.FromString,
                    response_serializer=kotlin__grpc__service_dot_message__pb2.GetMessagesResponse.SerializeToString,
            ),
            'GetMessageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMessageStream,
                    request_deserializer=kotlin__grpc__service_dot_message__pb2.GetMessageStreamRequest.FromString,
                    response_serializer=kotlin__grpc__service_dot_message__pb2.GetMessageStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doordash_kotlin_grpc_service.KotlinGRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doordash_kotlin_grpc_service.KotlinGRPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KotlinGRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMessageForSQSExample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doordash_kotlin_grpc_service.KotlinGRPCService/CreateMessageForSQSExample',
            kotlin__grpc__service_dot_message__pb2.CreateMessageRequest.SerializeToString,
            kotlin__grpc__service_dot_message__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessagesFromSQSExample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doordash_kotlin_grpc_service.KotlinGRPCService/GetMessagesFromSQSExample',
            kotlin__grpc__service_dot_message__pb2.EmptyRequest.SerializeToString,
            kotlin__grpc__service_dot_message__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/doordash_kotlin_grpc_service.KotlinGRPCService/GetMessageStream',
            kotlin__grpc__service_dot_message__pb2.GetMessageStreamRequest.SerializeToString,
            kotlin__grpc__service_dot_message__pb2.GetMessageStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
