# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kotlin_grpc_service/message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kotlin_grpc_service/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import service_client_config_pb2 as common_dot_service__client__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!kotlin_grpc_service/message.proto\x12\x1c\x64oordash_kotlin_grpc_service\x1a\"common/service_client_config.proto\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponse\"\x19\n\x17GetMessageStreamRequest\"\'\n\x14\x43reateMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x13GetMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"+\n\x18GetMessageStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc1\x03\n\x11KotlinGRPCService\x12\x86\x01\n\x1a\x43reateMessageForSQSExample\x12\x32.doordash_kotlin_grpc_service.CreateMessageRequest\x1a+.doordash_kotlin_grpc_service.EmptyResponse\"\x07\xc2\xdd \x03\x08\x84\x07\x12\x84\x01\n\x19GetMessagesFromSQSExample\x12*.doordash_kotlin_grpc_service.EmptyRequest\x1a\x31.doordash_kotlin_grpc_service.GetMessagesResponse\"\x08\xc2\xdd \x04\x12\x02\x18\x03\x12\x83\x01\n\x10GetMessageStream\x12\x35.doordash_kotlin_grpc_service.GetMessageStreamRequest\x1a\x36.doordash_kotlin_grpc_service.GetMessageStreamResponse0\x01\x1a\x16\xf2\xed\x1e\x12\x18\xa0\x06\"\t\x18\x03*\x02\x08\r2\x01\n*\x02\x10\x14\x42.\n\x1b\x63om.doordash.rpc.kotlingrpcP\x01Z\nkotlingrpc\x88\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kotlin_grpc_service.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.doordash.rpc.kotlingrpcP\001Z\nkotlingrpc\210\001\001'
  _globals['_KOTLINGRPCSERVICE']._loaded_options = None
  _globals['_KOTLINGRPCSERVICE']._serialized_options = b'\362\355\036\022\030\240\006\"\t\030\003*\002\010\r2\001\n*\002\020\024'
  _globals['_KOTLINGRPCSERVICE'].methods_by_name['CreateMessageForSQSExample']._loaded_options = None
  _globals['_KOTLINGRPCSERVICE'].methods_by_name['CreateMessageForSQSExample']._serialized_options = b'\302\335 \003\010\204\007'
  _globals['_KOTLINGRPCSERVICE'].methods_by_name['GetMessagesFromSQSExample']._loaded_options = None
  _globals['_KOTLINGRPCSERVICE'].methods_by_name['GetMessagesFromSQSExample']._serialized_options = b'\302\335 \004\022\002\030\003'
  _globals['_EMPTYREQUEST']._serialized_start=103
  _globals['_EMPTYREQUEST']._serialized_end=117
  _globals['_EMPTYRESPONSE']._serialized_start=119
  _globals['_EMPTYRESPONSE']._serialized_end=134
  _globals['_GETMESSAGESTREAMREQUEST']._serialized_start=136
  _globals['_GETMESSAGESTREAMREQUEST']._serialized_end=161
  _globals['_CREATEMESSAGEREQUEST']._serialized_start=163
  _globals['_CREATEMESSAGEREQUEST']._serialized_end=202
  _globals['_GETMESSAGESRESPONSE']._serialized_start=204
  _globals['_GETMESSAGESRESPONSE']._serialized_end=243
  _globals['_GETMESSAGESTREAMRESPONSE']._serialized_start=245
  _globals['_GETMESSAGESTREAMRESPONSE']._serialized_end=288
  _globals['_KOTLINGRPCSERVICE']._serialized_start=291
  _globals['_KOTLINGRPCSERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
