# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/dasher_location_track_segment_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/dasher_location_track_segment_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?delivery_experience/dasher_location_track_segment_message.proto\x12\x16\x64\x65livery_experience.v1\"\xad\x01\n#DasherLocationMissingSegmentMessage\x12\x15\n\rdelivery_uuid\x18\x01 \x01(\t\x12\x11\n\tdasher_id\x18\x02 \x01(\t\x12\x15\n\rots_timestamp\x18\x03 \x01(\t\x12 \n\x18\x63hecked_location_service\x18\x04 \x01(\x08\x12#\n\x1b\x66ound_from_location_service\x18\x05 \x01(\x08\x42\x32\n\x13\x64\x65livery.experienceB\x13SegmentMessageProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.dasher_location_track_segment_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\023SegmentMessageProtoP\001\242\002\003HLW'
  _globals['_DASHERLOCATIONMISSINGSEGMENTMESSAGE']._serialized_start=92
  _globals['_DASHERLOCATIONMISSINGSEGMENTMESSAGE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
