# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/hello_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/hello_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'delivery_experience/hello_service.proto\x12\x16\x64\x65livery_experience.v1\"\x18\n\x08Greeting\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08response\x18\x01 \x01(\t2T\n\x07Greeter\x12I\n\x04send\x12 .delivery_experience.v1.Greeting\x1a\x1d.delivery_experience.v1.Reply\"\x00\x42\x30\n\x13\x64\x65livery.experienceB\x11HelloServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.hello_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\021HelloServiceProtoP\001\242\002\003HLW'
  _globals['_GREETING']._serialized_start=67
  _globals['_GREETING']._serialized_end=91
  _globals['_REPLY']._serialized_start=93
  _globals['_REPLY']._serialized_end=118
  _globals['_GREETER']._serialized_start=120
  _globals['_GREETER']._serialized_end=204
# @@protoc_insertion_point(module_scope)
