# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/live_activity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/live_activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from delivery_experience import order_status_pb2 as delivery__experience_dot_order__status__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'delivery_experience/live_activity.proto\x12\x16\x64\x65livery_experience.v1\x1a&delivery_experience/order_status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xae\x07\n\x0cLiveActivity\x12\x32\n\x0corder_status\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x37\n\x13\x61\x63tivity_created_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\norder_uuid\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x33\n\rdelivery_uuid\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07user_id\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12H\n\x13live_activity_model\x18\x06 \x01(\x0b\x32+.delivery_experience.v1.LiveActivityDetails\x12<\n\x16\x65ta_event_generated_id\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x37\n\x11\x64\x65livery_event_id\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12=\n\x07trigger\x18\t \x01(\x0b\x32,.delivery_experience.v1.LiveActivity.Trigger\x12/\n\x0bis_terminal\x18\n \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12.\n\ndismiss_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\xb9\x02\n\x07Trigger\x12+\n\x05topic\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06reason\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08\x65vent_id\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12;\n\x15source_event_category\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x37\n\x11source_event_uuid\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValueB>\n\x13\x64\x65livery.experienceB\x11LiveActivityProtoP\x01\xa2\x02\x11LiveActivityProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.live_activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\021LiveActivityProtoP\001\242\002\021LiveActivityProto'
  _globals['_LIVEACTIVITY']._serialized_start=173
  _globals['_LIVEACTIVITY']._serialized_end=1115
  _globals['_LIVEACTIVITY_TRIGGER']._serialized_start=802
  _globals['_LIVEACTIVITY_TRIGGER']._serialized_end=1115
# @@protoc_insertion_point(module_scope)
