# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/notifications_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/notifications_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from state_change_events import delivery_state_change_pb2 as state__change__events_dot_delivery__state__change__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/delivery_experience/notifications_service.proto\x12\x16\x64\x65livery_experience.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a/state_change_events/delivery_state_change.proto\"P\n\x1bHandleLifecycleEventRequest\x12\x31\n\x05\x65vent\x18\x01 \x01(\x0b\x32\".state_change_events.DeliveryEvent\"5\n\x1cHandleLifecycleEventResponse\x12\x15\n\rdelivery_uuid\x18\x01 \x01(\t\"\xc5\x02\n\x11NotificationEvent\x12\x30\n\ncreator_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12)\n\x03msg\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x33\n\rdelivery_uuid\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0ctemplate_key\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0corder_status\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\x10order_sub_status\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue2\x9c\x01\n\x14NotificationsService\x12\x83\x01\n\x14HandleLifecycleEvent\x12\x33.delivery_experience.v1.HandleLifecycleEventRequest\x1a\x34.delivery_experience.v1.HandleLifecycleEventResponse\"\x00\x42\x1a\n\x13\x64\x65livery.experienceP\x01\x88\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.notifications_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceP\001\210\001\001'
  _globals['_HANDLELIFECYCLEEVENTREQUEST']._serialized_start=189
  _globals['_HANDLELIFECYCLEEVENTREQUEST']._serialized_end=269
  _globals['_HANDLELIFECYCLEEVENTRESPONSE']._serialized_start=271
  _globals['_HANDLELIFECYCLEEVENTRESPONSE']._serialized_end=324
  _globals['_NOTIFICATIONEVENT']._serialized_start=327
  _globals['_NOTIFICATIONEVENT']._serialized_end=652
  _globals['_NOTIFICATIONSSERVICE']._serialized_start=655
  _globals['_NOTIFICATIONSSERVICE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
