# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/order_release.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/order_release.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'delivery_experience/order_release.proto\x12\x16\x64\x65livery_experience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n\'UpdateOrderReleaseEventTimestampRequest\x12\x15\n\rdelivery_uuid\x18\x01 \x01(\t\x12W\n\x04type\x18\x02 \x01(\x0e\x32I.delivery_experience.v1.UpdateOrderReleaseEventTimestampRequest.EventType\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"B\n\tEventType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tATTEMPTED\x10\x01\x12\r\n\tSUCCEEDED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\"*\n(UpdateOrderReleaseEventTimestampResponse2\xbd\x01\n\x13OrderReleaseService\x12\xa5\x01\n UpdateOrderReleaseEventTimestamp\x12?.delivery_experience.v1.UpdateOrderReleaseEventTimestampRequest\x1a@.delivery_experience.v1.UpdateOrderReleaseEventTimestampResponseB(\n\x13\x64\x65livery.experienceB\x0fOrderReleaseAPIP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.order_release_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\017OrderReleaseAPIP\001'
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPREQUEST']._serialized_start=101
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPREQUEST']._serialized_end=369
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPREQUEST_EVENTTYPE']._serialized_start=303
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPREQUEST_EVENTTYPE']._serialized_end=369
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPRESPONSE']._serialized_start=371
  _globals['_UPDATEORDERRELEASEEVENTTIMESTAMPRESPONSE']._serialized_end=413
  _globals['_ORDERRELEASESERVICE']._serialized_start=416
  _globals['_ORDERRELEASESERVICE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
