# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/order_health_monitor_tracking_event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/order_health_monitor_tracking_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=delivery_experience/order_health_monitor_tracking_event.proto\x12\x16\x64\x65livery_experience.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x03\n#LimboOrderCancellationTrackingEvent\x12\x31\n\x0b\x64\x65livery_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\norder_uuid\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x0b\x63onsumer_id\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12>\n\x18\x63onsumer_sanitized_email\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x33\n\rdispatch_link\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12)\n\x03gov\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\"\n\x13\x64\x65livery.experienceB\x03OHMP\x01\xa2\x02\x03OHMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.order_health_monitor_tracking_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\003OHMP\001\242\002\003OHM'
  _globals['_LIMBOORDERCANCELLATIONTRACKINGEVENT']._serialized_start=155
  _globals['_LIMBOORDERCANCELLATIONTRACKINGEVENT']._serialized_end=552
# @@protoc_insertion_point(module_scope)
