# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/ots_delivery_lifecycle_event_consumed_track_event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/ots_delivery_lifecycle_event_consumed_track_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKdelivery_experience/ots_delivery_lifecycle_event_consumed_track_event.proto\x12\x16\x64\x65livery_experience.v1\"\xf6\x01\n.OTSDeliveryLifecycleEventConsumedTrackingEvent\x12\x15\n\rdelivery_uuid\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65livery_id\x18\x02 \x01(\t\x12!\n\x19lifecycle_event_timestamp\x18\x03 \x01(\t\x12\x1c\n\x14ots_server_timestamp\x18\x04 \x01(\t\x12\x1e\n\x16write_to_redis_succeed\x18\x05 \x01(\x08\x12\x1b\n\x13\x64\x65livery_event_case\x18\x06 \x01(\t\x12\x1a\n\x12not_write_to_redis\x18\x07 \x01(\tBC\n\x13\x64\x65livery.experienceB$OTSDeliveryLifecycleEventIguazuTrackP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.ots_delivery_lifecycle_event_consumed_track_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB$OTSDeliveryLifecycleEventIguazuTrackP\001\242\002\003HLW'
  _globals['_OTSDELIVERYLIFECYCLEEVENTCONSUMEDTRACKINGEVENT']._serialized_start=104
  _globals['_OTSDELIVERYLIFECYCLEEVENTCONSUMEDTRACKINGEVENT']._serialized_end=350
# @@protoc_insertion_point(module_scope)
