# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/reorder_experience.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/reorder_experience.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import post_checkout_pb2 as common_dot_post__checkout__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,delivery_experience/reorder_experience.proto\x12\x16\x64\x65livery_experience.v1\x1a\x1a\x63ommon/post_checkout.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa7\x01\n\x11ReorderExperience\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.delivery_experience.v1.ReorderExperienceType\x12\x41\n\x10sdui_api_details\x18\x03 \x01(\x0b\x32\'.common.post_checkout.v1.SduiApiDetailsJ\x04\x08\x02\x10\x03R\x0csdui_details*\x8a\x02\n\x15ReorderExperienceType\x12\'\n#REORDER_EXPERIENCE_TYPE_UNSPECIFIED\x10\x00\x12\x38\n4REORDER_EXPERIENCE_TYPE_ONE_CLICK_REORDER_AND_REFUND\x10\x01\x12*\n&REORDER_EXPERIENCE_TYPE_SIMILAR_STORES\x10\x02\x12\x35\n1REORDER_EXPERIENCE_TYPE_SIMILAR_STORES_FOR_CX_CLX\x10\x03\x12+\n\'REORDER_EXPERIENCE_TYPE_STORE_CAROUSELS\x10\x04\x42H\n\x13\x64\x65livery.experienceB\x16ReorderExperienceProtoP\x01\xa2\x02\x16ReorderExperienceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.reorder_experience_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\026ReorderExperienceProtoP\001\242\002\026ReorderExperienceProto'
  _globals['_REORDEREXPERIENCETYPE']._serialized_start=303
  _globals['_REORDEREXPERIENCETYPE']._serialized_end=569
  _globals['_REORDEREXPERIENCE']._serialized_start=133
  _globals['_REORDEREXPERIENCE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
