# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/shadow_logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/shadow_logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(delivery_experience/shadow_logging.proto\x12\x16\x64\x65livery_experience.v1\"z\n\x10ShadowLogMessage\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65viceTimestamp\x18\x02 \x01(\t\x12\x1d\n\x15newOrderStatusPayload\x18\x03 \x01(\t\x12\x1d\n\x15oldOrderStatusPayload\x18\x04 \x01(\tB6\n\x13\x64\x65livery.experienceB\x17ShadowLogSegmentMessageP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.shadow_logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023delivery.experienceB\027ShadowLogSegmentMessageP\001\242\002\003HLW'
  _globals['_SHADOWLOGMESSAGE']._serialized_start=68
  _globals['_SHADOWLOGMESSAGE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
