# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_experience/presentation_gateway/order_tracking.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_experience/presentation_gateway/order_tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from delivery_experience import order_tracker_service_pb2 as delivery__experience_dot_order__tracker__service__pb2
from doordash.api import annotations_pb2 as doordash_dot_api_dot_annotations__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=delivery_experience/presentation_gateway/order_tracking.proto\x12\x03pco\x1a/delivery_experience/order_tracker_service.proto\x1a\x1e\x64oordash.api/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf4\x01\n\x15GetOrderStatusRequest\x12;\n\x13merchant_order_uuid\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12\x38\n\x10merchant_cart_id\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12\x38\n\x0b\x63onsumer_id\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x05\xf0\xea\x8b/\x00\x12\x16\n\x07user_id\x18\x05 \x01(\tB\x05\xf0\xea\x8b/\x03\x42\x12\n\x10order_identifier\"X\n\x16GetOrderStatusResponse\x12>\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x30.delivery_experience.v1.GetOrderStatusV2Response2\x99\x03\n\x18MarketplaceOrderTracking\x12\xe5\x01\n\x0eGetOrderStatus\x12\x1a.pco.GetOrderStatusRequest\x1a\x1b.pco.GetOrderStatusResponse\"\x99\x01\xca\xea\x8b/]\"\x01\x02*\x10\x08\x01\x10\xe8\x07\x18\xb8\x17 \xac\x02-\xcd\xcc\xc7\x42\x32\x01\x00jApco-marketplace-order-tracking-get-order-status.service.prod.ddsdx\x01\x82\xd3\xe4\x93\x02\x31\x12//marketplace-order-tracking/v1/get-order-status\x1a\x94\x01\xd2\xea\x8b/\x8e\x01\nm\n\rpost-checkout\x12$post-checkout-delivery-experience-de\x1a\x15#post-checkout-oncall\"\x1fteam-post-checkout@doordash.com2\x1amarketplace-order-trackingJ\x01\x00\x42\x41\n\x1f\x63om.doordash.postcheckout.protoP\x01\x88\x01\x01\xa2\x02\x18MarketplaceOrderTrackingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_experience.presentation_gateway.order_tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.doordash.postcheckout.protoP\001\210\001\001\242\002\030MarketplaceOrderTracking'
  _globals['_GETORDERSTATUSREQUEST'].fields_by_name['consumer_id']._loaded_options = None
  _globals['_GETORDERSTATUSREQUEST'].fields_by_name['consumer_id']._serialized_options = b'\360\352\213/\000'
  _globals['_GETORDERSTATUSREQUEST'].fields_by_name['user_id']._loaded_options = None
  _globals['_GETORDERSTATUSREQUEST'].fields_by_name['user_id']._serialized_options = b'\360\352\213/\003'
  _globals['_MARKETPLACEORDERTRACKING']._loaded_options = None
  _globals['_MARKETPLACEORDERTRACKING']._serialized_options = b'\322\352\213/\216\001\nm\n\rpost-checkout\022$post-checkout-delivery-experience-de\032\025#post-checkout-oncall\"\037team-post-checkout@doordash.com2\032marketplace-order-trackingJ\001\000'
  _globals['_MARKETPLACEORDERTRACKING'].methods_by_name['GetOrderStatus']._loaded_options = None
  _globals['_MARKETPLACEORDERTRACKING'].methods_by_name['GetOrderStatus']._serialized_options = b'\312\352\213/]\"\001\002*\020\010\001\020\350\007\030\270\027 \254\002-\315\314\307B2\001\000jApco-marketplace-order-tracking-get-order-status.service.prod.ddsdx\001\202\323\344\223\0021\022//marketplace-order-tracking/v1/get-order-status'
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=246
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=490
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=492
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=580
  _globals['_MARKETPLACEORDERTRACKING']._serialized_start=583
  _globals['_MARKETPLACEORDERTRACKING']._serialized_end=992
# @@protoc_insertion_point(module_scope)
