# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_service_pb2 as hello__service__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send = channel.unary_unary(
        '/delivery.experience.Greeter/send',
        request_serializer=hello__service__pb2.Greeting.SerializeToString,
        response_deserializer=hello__service__pb2.Reply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=hello__service__pb2.Greeting.FromString,
          response_serializer=hello__service__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'delivery.experience.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
