# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_service.proto',
  package='delivery.experience',
  syntax='proto3',
  serialized_options=b'\n\023delivery.experienceB\021HelloServiceProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x13hello_service.proto\x12\x13\x64\x65livery.experience\"\x18\n\x08Greeting\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08response\x18\x01 \x01(\t2N\n\x07Greeter\x12\x43\n\x04send\x12\x1d.delivery.experience.Greeting\x1a\x1a.delivery.experience.Reply\"\x00\x42\x30\n\x13\x64\x65livery.experienceB\x11HelloServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='delivery.experience.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='delivery.experience.Greeting.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=68,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='delivery.experience.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='delivery.experience.Reply.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'hello_service_pb2'
  # @@protoc_insertion_point(class_scope:delivery.experience.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'hello_service_pb2'
  # @@protoc_insertion_point(class_scope:delivery.experience.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='delivery.experience.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='delivery.experience.Greeter.send',
    index=0,
    containing_service=None,
    input_type=_GREETING,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
