# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class KotlinGRPCServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateMessageForSQSExample = channel.unary_unary(
        '/doordash_kotlin_grpc_service.KotlinGRPCService/CreateMessageForSQSExample',
        request_serializer=message__pb2.CreateMessageRequest.SerializeToString,
        response_deserializer=message__pb2.EmptyResponse.FromString,
        )
    self.GetMessagesFromSQSExample = channel.unary_unary(
        '/doordash_kotlin_grpc_service.KotlinGRPCService/GetMessagesFromSQSExample',
        request_serializer=message__pb2.EmptyRequest.SerializeToString,
        response_deserializer=message__pb2.GetMessagesResponse.FromString,
        )


class KotlinGRPCServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateMessageForSQSExample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMessagesFromSQSExample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KotlinGRPCServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateMessageForSQSExample': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMessageForSQSExample,
          request_deserializer=message__pb2.CreateMessageRequest.FromString,
          response_serializer=message__pb2.EmptyResponse.SerializeToString,
      ),
      'GetMessagesFromSQSExample': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessagesFromSQSExample,
          request_deserializer=message__pb2.EmptyRequest.FromString,
          response_serializer=message__pb2.GetMessagesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'doordash_kotlin_grpc_service.KotlinGRPCService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
