# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from case_management_service.salesforce import salesforce_pb2 as case__management__service_dot_salesforce_dot_salesforce__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in case_management_service/salesforce/salesforce_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesforceGatewayServiceStub(object):
    """API that is a gateway to Salesforce
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesforceActiveCasesByAgent = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceActiveCasesByAgent',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentResponse.FromString,
                _registered_method=True)
        self.GetSalesforceCasesByDeliveryUuid = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCasesByDeliveryUuid',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidResponse.FromString,
                _registered_method=True)
        self.GetSalesforceUserId = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceUserId',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdResponse.FromString,
                _registered_method=True)
        self.GetSalesforceCasesByCaseNumber = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCasesByCaseNumber',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberResponse.FromString,
                _registered_method=True)
        self.CreateSalesforceChatTranscript = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/CreateSalesforceChatTranscript',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptResponse.FromString,
                _registered_method=True)
        self.CloseSalesforceCase = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/CloseSalesforceCase',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseResponse.FromString,
                _registered_method=True)
        self.GetSalesforceCaseHistory = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseHistory',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryResponse.FromString,
                _registered_method=True)
        self.GetSalesforceEmails = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceEmails',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsResponse.FromString,
                _registered_method=True)
        self.GetSalesforceCaseFeed = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseFeed',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedResponse.FromString,
                _registered_method=True)
        self.SignEmailAttachmentMetadata = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/SignEmailAttachmentMetadata',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataResponse.FromString,
                _registered_method=True)
        self.GetRecentDasherAppeals = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetRecentDasherAppeals',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsResponse.FromString,
                _registered_method=True)
        self.GetSalesforceCaseDetails = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseDetails',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsResponse.FromString,
                _registered_method=True)
        self.GetAmazonConnectContactTraceRecords = channel.unary_unary(
                '/case_management_service.salesforce.v1.SalesforceGatewayService/GetAmazonConnectContactTraceRecords',
                request_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsRequest.SerializeToString,
                response_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsResponse.FromString,
                _registered_method=True)


class SalesforceGatewayServiceServicer(object):
    """API that is a gateway to Salesforce
    """

    def GetSalesforceActiveCasesByAgent(self, request, context):
        """Gets the active cases assigned to the provided user.
        Returns subset of data from ERS getSalesforceCasesSummaryBySalesforceUserId
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceCasesByDeliveryUuid(self, request, context):
        """Gets salesforce cases for a provided delivery uuid
        Returns subset of data from ERS getSalesforceCasesSummaryByDeliveryUuid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceUserId(self, request, context):
        """Maps DoorDash email address to Salesforce User ID
        Returns subset of data from ERS getSalesforceContext
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceCasesByCaseNumber(self, request, context):
        """Loads salesforce case by case number
        Returns subset of data from ERS getSalesforceCasesSummaryByCaseNums
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSalesforceChatTranscript(self, request, context):
        """Method to create a chat transcript at Salesforce
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSalesforceCase(self, request, context):
        """Method to close a salesforce case.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceCaseHistory(self, request, context):
        """Loads Salesforce Case History
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceEmails(self, request, context):
        """Load Salesforce Emails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceCaseFeed(self, request, context):
        """Loads Salesforce Case Feed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignEmailAttachmentMetadata(self, request, context):
        """Signs attachment metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentDasherAppeals(self, request, context):
        """Gets recent Dasher Appeals cases
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesforceCaseDetails(self, request, context):
        """Loads Salesforce Case History, case feed and emails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAmazonConnectContactTraceRecords(self, request, context):
        """Gets GetAmazonConnectContactTraceRecords given a contactId
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesforceGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesforceActiveCasesByAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceActiveCasesByAgent,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentResponse.SerializeToString,
            ),
            'GetSalesforceCasesByDeliveryUuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceCasesByDeliveryUuid,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidResponse.SerializeToString,
            ),
            'GetSalesforceUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceUserId,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdResponse.SerializeToString,
            ),
            'GetSalesforceCasesByCaseNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceCasesByCaseNumber,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberResponse.SerializeToString,
            ),
            'CreateSalesforceChatTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSalesforceChatTranscript,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptResponse.SerializeToString,
            ),
            'CloseSalesforceCase': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSalesforceCase,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseResponse.SerializeToString,
            ),
            'GetSalesforceCaseHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceCaseHistory,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryResponse.SerializeToString,
            ),
            'GetSalesforceEmails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceEmails,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsResponse.SerializeToString,
            ),
            'GetSalesforceCaseFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceCaseFeed,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedResponse.SerializeToString,
            ),
            'SignEmailAttachmentMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SignEmailAttachmentMetadata,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataResponse.SerializeToString,
            ),
            'GetRecentDasherAppeals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentDasherAppeals,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsResponse.SerializeToString,
            ),
            'GetSalesforceCaseDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesforceCaseDetails,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsResponse.SerializeToString,
            ),
            'GetAmazonConnectContactTraceRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAmazonConnectContactTraceRecords,
                    request_deserializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsRequest.FromString,
                    response_serializer=case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'case_management_service.salesforce.v1.SalesforceGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('case_management_service.salesforce.v1.SalesforceGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesforceGatewayService(object):
    """API that is a gateway to Salesforce
    """

    @staticmethod
    def GetSalesforceActiveCasesByAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceActiveCasesByAgent',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceActiveCasesByAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceCasesByDeliveryUuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCasesByDeliveryUuid',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByDeliveryUuidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceUserId',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceUserIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceCasesByCaseNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCasesByCaseNumber',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCasesByCaseNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSalesforceChatTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/CreateSalesforceChatTranscript',
            case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.CreateSalesforceChatTranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSalesforceCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/CloseSalesforceCase',
            case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.CloseSalesforceCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceCaseHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseHistory',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceEmails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceEmails',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceEmailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceCaseFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseFeed',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignEmailAttachmentMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/SignEmailAttachmentMetadata',
            case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.SignEmailAttachmentMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentDasherAppeals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetRecentDasherAppeals',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetRecentDasherAppealsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesforceCaseDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetSalesforceCaseDetails',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetSalesforceCaseDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAmazonConnectContactTraceRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/case_management_service.salesforce.v1.SalesforceGatewayService/GetAmazonConnectContactTraceRecords',
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsRequest.SerializeToString,
            case__management__service_dot_salesforce_dot_salesforce__pb2.GetAmazonConnectContactTraceRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
