# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/dayparts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common/dayparts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/dayparts.proto\x12\x08\x64\x61yparts\"\x83\x01\n\x07\x44\x61yPart\x12<\n\x19start_time_of_day_of_week\x18\x01 \x01(\x0b\x32\x19.dayparts.TimeOfDayOfWeek\x12:\n\x17\x65nd_time_of_day_of_week\x18\x02 \x01(\x0b\x32\x19.dayparts.TimeOfDayOfWeek\"e\n\x0fTimeOfDayOfWeek\x12(\n\x0b\x64\x61y_of_week\x18\x01 \x01(\x0e\x32\x13.dayparts.DayOfWeek\x12(\n\x0btime_of_day\x18\x02 \x01(\x0b\x32\x13.dayparts.TimeOfDay\"K\n\tTimeOfDay\x12\r\n\x05hours\x18\x01 \x01(\x05\x12\x0f\n\x07minutes\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x05\x12\r\n\x05nanos\x18\x04 \x01(\x05*\x84\x01\n\tDayOfWeek\x12\x1b\n\x17\x44\x41Y_OF_WEEK_UNSPECIFIED\x10\x00\x12\n\n\x06MONDAY\x10\x01\x12\x0b\n\x07TUESDAY\x10\x02\x12\r\n\tWEDNESDAY\x10\x03\x12\x0c\n\x08THURSDAY\x10\x04\x12\n\n\x06\x46RIDAY\x10\x05\x12\x0c\n\x08SATURDAY\x10\x06\x12\n\n\x06SUNDAY\x10\x07\x42V\n\x17\x63om.doordash.rpc.commonP\x01Z6github.com/doordash/services-protobuf/generated/common\x88\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.dayparts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.doordash.rpc.commonP\001Z6github.com/doordash/services-protobuf/generated/common\210\001\001'
  _globals['_DAYOFWEEK']._serialized_start=350
  _globals['_DAYOFWEEK']._serialized_end=482
  _globals['_DAYPART']._serialized_start=36
  _globals['_DAYPART']._serialized_end=167
  _globals['_TIMEOFDAYOFWEEK']._serialized_start=169
  _globals['_TIMEOFDAYOFWEEK']._serialized_end=270
  _globals['_TIMEOFDAY']._serialized_start=272
  _globals['_TIMEOFDAY']._serialized_end=347
# @@protoc_insertion_point(module_scope)
