# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/names.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common/names.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/names.proto\x12\x05names\x1a\x1egoogle/protobuf/wrappers.proto\"\xe2\x02\n\x0eLocalizedNames\x12\x37\n\rinformal_name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x02\x18\x01\x12\x35\n\x0b\x66ormal_name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x02\x18\x01\x12\x41\n\x17\x66ormal_name_abbreviated\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x02\x18\x01\x12\x30\n\nshort_name\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12:\n\x14\x66ull_privatized_name\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\tfull_name\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\\\n\x1d\x63om.doordash.rpc.common.namesP\x01Z6github.com/doordash/services-protobuf/generated/common\x88\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.names_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.doordash.rpc.common.namesP\001Z6github.com/doordash/services-protobuf/generated/common\210\001\001'
  _globals['_LOCALIZEDNAMES'].fields_by_name['informal_name']._loaded_options = None
  _globals['_LOCALIZEDNAMES'].fields_by_name['informal_name']._serialized_options = b'\030\001'
  _globals['_LOCALIZEDNAMES'].fields_by_name['formal_name']._loaded_options = None
  _globals['_LOCALIZEDNAMES'].fields_by_name['formal_name']._serialized_options = b'\030\001'
  _globals['_LOCALIZEDNAMES'].fields_by_name['formal_name_abbreviated']._loaded_options = None
  _globals['_LOCALIZEDNAMES'].fields_by_name['formal_name_abbreviated']._serialized_options = b'\030\001'
  _globals['_LOCALIZEDNAMES']._serialized_start=62
  _globals['_LOCALIZEDNAMES']._serialized_end=416
# @@protoc_insertion_point(module_scope)
